export const ActionTypes = {
	TOGGLE_BOOKLIST: 'TOGGLE_BOOKLIST',
	FETCH_BOOKS_START: 'FETCH_BOOKS_START',
	FETCH_BOOKS_SUCCESS: 'FETCH_BOOKS_SUCCESS',
	FETCH_BOOKS_FAILURE: 'FETCH_BOOKS_FAILURE',
	ADD_BOOK: 'ADD_BOOK'
};
